- name: Include shared Docker config task
  ansible.builtin.include_tasks: ../../tasks/configure_docker.yml
  vars:
    registry_address: "172.10.10.200:5000"

- name: Include shared restart task
  ansible.builtin.include_tasks: ../../tasks/restart_service.yml
  vars:
    service_name: docker