ARG BASE_IMAGE=debian:bullseye
FROM ${BASE_IMAGE}

LABEL maintainer="Parsa Khaledi <pa.aerospace@gmail.com>"

SHELL ["/bin/bash", "-c"]

ARG USER_NAME=rpi
ARG USER_UID=1000
ARG USER_GID=1000

ENV DEBIAN_FRONTEND=noninteractive
ENV QT_X11_NO_MITSHM=1
ENV LANG=en_US.UTF-8
ENV WORK_DIR=/${USER_NAME}/ws_px4
WORKDIR ${WORK_DIR}

RUN apt -y update && \
    apt -y install --no-install-recommends \
        git vim parted \
        quilt coreutils  zip\
        libarchive-tools libcap2-bin rsync grep udev xz-utils curl git file kmod  \
        gpg \
    && rm -rf /var/lib/apt/lists/*

### Set User	
RUN groupadd ${USER_NAME} --gid ${USER_GID} && \
    useradd -l -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -s /bin/bash && \
	echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME} && \
	mkdir -p /home/${USER_NAME} && \
	chmod 0440 /etc/sudoers.d/${USER_NAME} && chown -R ${USER_NAME}:${USER_NAME} /${USER_NAME} 

### Change user
USER ${USER_NAME}
WORKDIR /home/${USER_NAME}


RUN git clone -b v1.6.3 https://github.com/raspberrypi/cmprovision.git && cd cmprovision &&\
    sudo apt install ./cmprovision4_*_all.deb 

# VOLUME [ "/cmprovisioner"]

### Finilize
RUN sudo rm -rf /var/lib/apt/lists/* &&\
	sudo apt autoremove -y

