version: '3.8'

services:
  registry:
    image: registry:3.0
    restart: unless-stopped
    ports:
      - "5000:5000"
      # - "4318:4318"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true" # Enable image deletion (use with caution)
    volumes:
      - registry-data:/var/lib/registry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/v2/"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - registry-network

  ansible:
    image: docker.io/alpine/ansible:2.18.1
    container_name: ansible
    hostname: host_ansible
    tty: true
    network_mode: "host"
    restart: unless-stopped
    # ports:
    #   - "20:20"
    volumes:
      - ./ansible:/ansible
      - ~/.ssh/:/ansible/keys:ro
    # networks:
    #   - registry-network
    command: /bin/bash -c "
      eval "$(ssh-agent)" && ssh-add /ansible/keys/remote && cd /ansible && \
      ansible-playbook -i inventory/hosts.yaml -l RPILtelink playbooks/postsetup_raylink/postsetup_raylink.yaml -vvv &&\
      sleep inf"
    nexus:
    image: sonatype/nexus3:3.79.1
    container_name: nexus
    ports:
      - "8081:8081" # Nexus UI and API – access it via http://localhost:8081
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped


  # provisioner:
  #   image: rpi:latest-build-20250501
  #   restart: unless-stopped
  #   network_mode: "host"
  #   # ports: 
  #   #   - "81:80"
  #   #   - "444:443"
  #   volumes:
  #     - cmprovision_uploads:/var/lib/cmprovision/public/uploads
  #     - cmprovision_db:/var/lib/cmprovision/database
  #     - cmprovision_logs:/var/lib/cmprovision/storage/logs
  #     - /etc/dhcpcd.conf:/etc/dhcpcd.conf
    
  #   command: /bin/bash -c ""

networks:
  registry-network:
    driver: bridge

volumes:
  registry-data:
  nexus-data:
  # cmprovision_uploads:
  # cmprovision_db:
  # cmprovision_logs:
