- name: Configure Docker for insecure registry
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ registry_address }}"]
      }
    mode: '0644'
