---
# - name: check chest_path
#   hosts: all
#   tasks:
#     - name: Print resolved user path
#       ansible.builtin.debug:
#         msg: "/home/{{ ansible_user }}/docker-compose.yml"
# - name: PostIntsall
#   hosts: all
#   roles:
#     - docker_configure

# - name: PostIntsall "docker config"
#   hosts: all
#   tasks:
#     - name: Apply docker_configure role
#       include_role:
#         name: docker_configure
#     - name: Docker Service Restart
#       ansible.builtin.include_tasks: ../../tasks/service_restart.yaml
#       vars:
#         service_name: docker

- name: PostIntsall "docker compose copy and up"
  hosts: all
  tasks:
    - name: Copy Docker compose file
      ansible.builtin.include_tasks: ../../tasks/copy_files.yaml
      vars:
        source_path: "{{ playbook_dir }}/files/docker-compose-localDockerregistery.yaml"
        dest_path: "/home/{{ ansible_user }}/docker-compose-localDockerregistery.yaml" 

    - name: Pull required Docker images
      ansible.builtin.include_tasks: ../../tasks/docker-compose_pull.yaml
      vars:
        docker_compose_file_name: "docker-compose-localDockerregistery.yaml"

    - name: Add docker compose up systemd service
      ansible.builtin.include_tasks: ../../tasks/systemd-docker-compose-up.yaml
      vars:
        compose_file_name: "docker-compose-localDockerregistery"

    # - roles/docker-compose_ready.yaml
# - hosts: RPILtelink
#   tasks:
#     - name: Copy file from Ansible host to remote
#       ansible.builtin.copy:
#         src: "{{ playbook_dir }}/files/docker-compose-localDockerregistery.yaml"
#         dest: "/home/{{ ansible_user }}/docker-compose-localDockerregistery.yaml"
#         mode: '0644'
