---
- name: ping
  hosts: all
  tasks:
    - name: ping hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Test Print Meesage 

- name: PostIntsall
  hosts: all
  roles:
    - docker_configure

